global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["10.0.0.5:9090"]

  - job_name: "lb-node"
    static_configs:
      - targets: ["10.0.0.2:9100", "10.0.0.2:9913"]

  - job_name: "web1-node"
    static_configs:
      - targets: ["10.0.0.10:9100", "10.0.0.10:9913"]

  - job_name: "web2-node"
    static_configs:
      - targets: ["10.0.0.11:9100", "10.0.0.11:9913"]
